### ISSUE TITLE
Track language versions of downloading users

### ISSUE THREAD

**Issue by bernardd** [hexpm/hexpm#1026]
As a maintainer it would be super valuable to know the version of the language (eg Elixir 1.9) that is being used by people downloading the package (and even better if that could be cross-correlated with which version of the package is being downloaded). This would make deciding when it's okay to drop support for older versions much easier. Thanks for an awesome service!

**Comment by ericmj** [comment]
We have refrained from providing this information because it's not accurate so there's a chance wrong conclusions will be drawn from it. We can't track this accurately because users are not represented equally, tracking downloads does not track users.

The majority of downloads happens from CI systems which means users with heavy CI usage would be overrepresented. In the same way, users that have many dependencies would be represented more than users with less.

In addition we cannot track end consumers of packages. When looking at my package's download stats, other libraries CI, that depend on my library, will be included in the stats. The other libraries may support down to an old Elixir version but I don't know if there are any actual end users of the libraries that use those old versions, because the stats are mixed with the libraries' own CI downloads.

**Comment by bernardd** [comment]
That's fair enough. Guess I'll have to figure out a better way to figure it out :) Thanks for the detailed response.
