### ISSUE TITLE
Make UI translatable

### ISSUE THREAD

**Issue by adamwight** [hexpm/hexpm#1097]
It would be nice if the hexpm web interface rendered in my browser's locale language by default.  Users would also want the ability to override via a language chooser with sticky cookie, or the logged-in user's saved preferences.

Taking the opportunity to quote an interesting statistic, something like 85% of the world's population doesn't speak English.[[1]](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers)

**Comment by ericmj** [comment]
I agree that this would be great but it's a very large task and too much work for the hex team to implement by ourselves.

We would also need to have a plan to ensure other languages are kept up to date with English since the team members may not know the other languages we would support.

@adamwight Are you willing to work on this or help us find people that are willing to work on it?

**Comment by adamwight** [comment]
I'd be happy to help with this.  My day job (MediaWiki development) involves l10n and I'm curious to see how Phoenix supports the issues around grammar, numbers, etc.  However, my Phoenix and Elixir experience only consists of a few "hello, world!" toys with multi-locale support, so I'll probably reach for the wrong paradigm.  If this kind of "learning on the job" doesn't sound too disruptive, then let's go ahead and try!

Glad to see that maintenance concerns are being discussed up front.  Ideally the translations can be collaboratively edited on a site like https://translatewiki.net/ or any other that supports gettext files, and volunteer translators will be motivated by having the software available in their preferred language.  Individual messages aren't expected to change very often, at least the meaning should stay the same.  More likely is that when you add new features, you'll also add new messages.  Until these messages have been translated, they appear as an English string alongside the native text.  In other words, any failures to keep translations up-to-date shouldn't make the software unusable but will only be a small inconvenience.

**Comment by adamwight** [comment]
Just so there's something concrete to talk about, I've made a rough pass at localizing the main landing page, [here](https://github.com/hexpm/hexpm/compare/main...adamwight:i18n?expand=1) .  Checking out that branch will force the language to Spanish as a demonstration.

One issue jumps out, that many messages need to be rendered without HTML escaping.  This is only safe if translations are being reviewed manually.  A smaller issue is that some of the strings include explicit formatting like `<br>` which is best left to CSS and the browser's layout engine.

**Comment by ericmj** [comment]
Thanks for opening the issue but it's too much maintenance to add multi language support to Hex. We are also in the middle of the redesigning the website so there would be many conflicts if we do it now.

If you want to improve the language support in the community I would suggest working on documentation for the Elixir website or popular libraries such as Phoenix or Ecto. Work on that will have higher impact and is easier to do since it's static content.
