### ISSUE TITLE
Autofocus "Authentication Code" field in Login

### ISSUE THREAD

**Issue by dmarcoux** [hexpm/hexpm#1175]
When logging in with two-factor authentication enabled, the _Search_ field is focused instead of the _Authentication Code_ field.

This is exactly the same as #823, but for 2FA. Here's the page:

![hexpm](https://user-images.githubusercontent.com/1102934/210083930-66dbfab9-de69-4324-93c8-b8a811acbc66.png)

**Comment by dmarcoux** [comment]
I could easily fix this, but somehow I cannot get the development environment running. The CSS and JS isn't loaded... Which version of Node is expected to be installed? And what about Yarn, any version will do? I tried with Node 18.12.1 and yarn 1.22.19, but it didn't work. I'm also running Elixir 1.14.2 with Erlang/OTP 25.

**Comment by nskins** [comment]
Hi @dmarcoux. If you're still interested to fix this issue, I'd like to help you get the CSS and JS working.

Before you run `mix phx.server`, make sure to run `cd assets && yarn install` or `cd assets && npm install`. This comes from the README, but I guess it's not really in the ideal order.

If you run into the same errors that I did, you'll also need to run `npx browserslist@latest --update-db` and `export NODE_OPTIONS=--openssl-legacy-provider`. You might not see those errors at all, but the commands are here in case you do! (For the second, you'll see a fairly obtuse error about crypto hashing.)

If you want to hand this issue off, I would be glad to take a look, but I want to make sure you can get a chance since it sounds like you were interested to write the code.

**Comment by Benjamin-Philip** [comment]
Hi @dmarcoux,

Since this was a 2 min job, I decided to fix this anyway. Like @nskins said, all you need to do is ` export NODE_OPTIONS=--openssl-legacy-provider` due to a bug in Node v18.12.

**Comment by dmarcoux** [comment]
@nskins I did run `cd assets && yarn install` before, but it didn't fix the issue. However, I didn't try the second command you wrote. I will give this a try.

@Benjamin-Philip No worries, thank you for handling this. I think it would be a good idea to document this `export NODE_OPTIONS` command. What do you think?

Setting up the development environment isn't overly complicated, but it feels like it could be simpler. I saw a PR regarding a Docker setup which was closed. Did you change your mind on that? What about using a Nix shell? I could submit a PR for this.

**Comment by Benjamin-Philip** [comment]
> Is it documented somewhere in this repository?

Nope. Copy and Pasted out of SO (at least that's what I did).

**Comment by Benjamin-Philip** [comment]
Honestly the only thing I would change in the current setup is webpack and replace it with esbuild. If we find a way to use jQuery without vendoring it ourselves, we can probably remove the dependency on Node and yarn entirely.

Ask @ericmj or @wojtekmach if such a PR will be accepted.

**Comment by dmarcoux** [comment]
Regarding the development environment, the Docker setup right now only includes a container for the Postgres database. It could also include Elixir, Node and Yarn. It would be the same reproducible setup for every developer. Now, it's more of a "it works on my machine" setup :shrug:.

**Comment by Benjamin-Philip** [comment]
> It could also include Elixir, Node and Yarn.

I does include all of those. All you have to do is `podman run` or `docker run`.

Here's the file for reference:

https://github.com/hexpm/hexpm/blob/9d27e1d2db41bb7655155129d035e0c97767c3f3/Dockerfile#L1-L48

**Comment by Benjamin-Philip** [comment]
> It could also include Elixir, Node and Yarn.

Yes the docker compose setup could include Elixir et al. Please file a seperate issue for this. We'll have to check with Eric and Wojtek if there are any caveats to the compose setup as they maintain and host the project.
