### ISSUE TITLE
Recently updated, does not display the RC version

### ISSUE THREAD

**Issue by Hentioe** [hexpm/hexpm#1200]
I found that the https://hex.pm/packages?sort=updated_at page does not display RC versions, which causes some packages to be updated and appear at the top of the page, but the version displayed is not the latest.

I have a project that automatically tracks the updates of packages on Hex.pm. Since this page does not show the RC versions of the packages, there is a case where a package is repeatedly updated (causing changes in ranking), but the version number remains the same, which causes a lot of confusion.

I would like to inquire if it is possible to display the latest version of packages, including the RC versions, for packages sorted by `updated_at`. Alternatively, is it possible to insert information about the latest version on the page?

**Comment by ericmj** [comment]
If you are writing automated tooling you should use the API instead of scraping the website. Does the corresponding API endpoint https://hex.pm/api/packages?sort=updated_at sort by the latest version with pre-releases? If not I think that should change.

But I don't think the website should show pre-releases on that page. Unfortunately there isn't an easy way to have the sort exclude pre-releases.

**Comment by Hentioe** [comment]
@ericmj Sorry, I didn't know there was an API. I might not have known for a long time if you didn't tell me. As the API response contains sufficient detailed information, this problem no longer exists. Thank you very much! 😆
