### ISSUE TITLE
Consider rebar3 plugins in dependents

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [hexpm/hexpm#1215]
👋 

Do you think it'd make sense to consider `rebar3`'s `project_plugins`, `plugins` and their use inside `profiles` as "dependents", for Hex.pm visibility purposes?

Cheers.

---

As in:

<img width="182" alt="image" src="https://github.com/hexpm/hexpm/assets/7303768/d76c351f-7f02-4788-a872-61790aebbd0a">

**Comment by ferd** [comment]
That's currently a limitation of rebar3 itself because plugins are not considered to be deps, nor locked as such. They have a different build and execution model that we never managed to fully put under tight control (you need to compile and build some plugins to even know what else you need to fetch at times) and we don't yet know how to do that without changing the building model.

Since rebar3 itself doesn't have a clear way of structuring this, it doesn't have any sensible data to provide to hex either.

**Comment by paulo-ferraz-oliveira** [comment]
Oh, Ok. I thought Hex actually parsed `rebar.config`, but it probably calls some `rebar3` function and acts on the output (?) Feel free to re-open if you think there's any advantage in having this visible... Thanks, @ferd.
