### ISSUE TITLE
show the last updated time for "most downloaded" on https://hex.pm

### ISSUE THREAD

**Issue by Dieken** [hexpm/hexpm#501]
I misunderstood those packages hadn't been updated for three years, that made me sad...  maybe add a row "updated xxx days ago"? I guess most people don't care the first publish time.

![image](https://cloud.githubusercontent.com/assets/2365/25692706/37e594da-30d7-11e7-89e0-e84eb1afe126.png)

**Comment by ericmj** [comment]
Even though some of those packages haven't been updated recently they are still the most used packages on Hex. I don't think last update is a good metric because few updates can also be a good thing since it shows the package is stable.

First published at is not a good metric either but we need something there for the design to look good and I think I slightly prefer it.

**Comment by ericmj** [comment]
I think only cowlib and poolboy are the only packages in that list that haven't had recent updates. They are used by phoenix and ecto because they are the best alternatives for what they do.

**Comment by Dieken** [comment]
Yes, actually most popular packages are still actively maintained, so I feel showing last update time will greatly encourage newbies, and also remind users of these popular packages to upgrade.

I'm not insisting on removing last publish time, this doesn't matter much, I'm hoping showing last update time.

Thanks for your quick response!

**Comment by michalmuskala** [comment]
I don't agree the last update time is a meaningful metric for a lot of libraries. It completely misses the point of libraries/packages being "complete" - and that definitely happens especially with smaller packages that do one thing well.
