### ISSUE TITLE
No way to resend account confirmation emails

### ISSUE THREAD

**Issue by rschmukler** [hexpm/hexpm#513]
When registering an account, if the email is undeliverable (eg. a glitch) you can hit a situation where there is no way into your account. You are unable to login (because the account is not yet confirmed) and you there is no way to re-trigger the delivery of the confirmation email.

If you attempt to re-register it will tell you that the username has already been taken.

**Comment by wojtekmach** [comment]
Good catch, I thought resetting password would work but it did not. Btw, if you did hit this problem please email support@hex.pm and we'll assist with setting up the account.

**Comment by rschmukler** [comment]
ericmj took care of me in the IRC but thank you

**Comment by zoldar** [comment]
What do you think about a following approach:

- Add ability to trigger password reset for any user, regardless if he has a verified email or not.
- When finalizing the reset request, always verify the user's primary email if it's not verified yet.

? 

Is there anything with regards to the safety measures that I'm missing, please let me know.

**Comment by wojtekmach** [comment]
the proposed flow sounds good to me, wdyt @ericmj?

**Comment by ericmj** [comment]
I think that flow makes sense, another idea would be to make it possible to register with an existing email if the email is not verified yet.

**Comment by zoldar** [comment]
> I think that flow makes sense, another idea would be to make it possible to register with an existing email if the email is not verified yet.

Both flows could be implemented to reduce the element of surprise.

In case of registering with existing email, the flow could be following:

- On initial registration request, try fetching user by the same username with no verified emails
  * If such user exists, remove him along with the email(s) and then proceed with creating the entry (thought about updating, but this may pose a risk of reusing unrelated previous entry's sensitive details)
  * Otherwise, proceed as usual

If this makes sense, I can work on that. I already made some preliminary work on password reset handling (having problems with tests not catching the regression though - need to investigate that).

**Comment by zoldar** [comment]
I have realized one fundamental problem with the altered password reset flow - there can be more than one instance of the same email (1 verified, several unverified at the same time). That makes it impossible to select a single user account on the basis of email alone. I also see no way to introduce such guarantee (there can be several pending, unverified entries for the same email address under different users).

**Comment by ericmj** [comment]
Then we should probably skip the changes to password resets and only allow reregistering an existing user with unverified email.
