### ISSUE TITLE
GitHub webhook

### ISSUE THREAD

**Issue by ddeboer** [hexpm/hexpm#514]
A problem with many packages on Hex.pm is that they aren’t up-to-date, even when new versions are tagged on GitHub.

As a workaround, I created [Hexpub](https://github.com/zotonic/hexpub), which automates publishing updates to Hex: every time a repository is tagged, an updated version will be pushed to Hex.

A better solution, of course, is to have proper GitHub integration. This can be done by adding a [GitHub webhook](https://developer.github.com/webhooks/) endpoint to Hex.pm (in particular, [CreateEvent](https://developer.github.com/v3/activity/events/types/#createevent)). Package maintainers can then add this webhook’s URL in their repository settings. The webhook should:

1. authenticate the call based on the Hex user’s API key
2. download the code from GitHub
3. publish it to Hex using either rebar3 or mix (depending on how the package was published before) with the Git tag as the version number; alternatively require `{vsn, "git"}`.

**Comment by ericmj** [comment]
I don't think publishing to Hex should be automated because it's easy to miss things and make mistakes so I wouldn't want hex.pm to support this.

But this service doesn't have to be part of hex.pm, you can set up your own service that listens to the github webhook and published the package.

**Comment by wojtekmach** [comment]
I also think that GitHub webhook is outside of Hex.pm's scope. IMHO Hexpub is actually a more versatile solution because it's independent of GitHub and would work with Gitlab, Bitbucket etc.

FWIW I think tags/version mismatch is a real problem. (shameless plug) I went the other way and created a tool that creates a tag on package publish: https://github.com/wojtekmach/publish_plus
