### ISSUE TITLE
URL is case sensitive

### ISSUE THREAD

**Issue by ardhitama** [hexpm/hexpm#521]
[https://hexdocs.pm/Elixir](https://hexdocs.pm/Elixir) returning `404`
while [https://hexdocs.pm/elixir](https://hexdocs.pm/elixir) is correct.

The exptected behaviour according to [rfc3986 section-6.2.2.1](https://tools.ietf.org/html/rfc3986#section-6.2.2.1)  an URL should be case-insensitive.

**Comment by ericmj** [comment]
Did you link to the wrong spec? According to what you linked only percent encoded triplets, scheme and hostname are case insensitive,  and everything else case sensitive.

We can't make /Elixir and /elixir have the same behaviour because the files are hosted by S3 which does not allow changing this. What we could try to do is to configure our CDN to always redirect to the lowercase path if there is an uppercase character, or normalize before doing the origin request but I'm not sure if this is possible.

**Comment by josevalim** [comment]
Yes, the spec only says percent encoding, scheme and hostname are case sensitive.

**Comment by ardhitama** [comment]
Apologies, yes I'm mistaken.
I experienced this when I want to open elixir doc from mix. It's just a convenience thing.

Closing.
