### ISSUE TITLE
As a user, I want to access the Elixir language documentation from the homepage so that I can have one access point to (and bookmark for) Elixir documentation

### ISSUE THREAD

**Issue by jfeaver** [hexpm/hexpm#557]
For example:

* Static links to https://hexdocs.pm/elixir/ and other contexts listed on the official docs page (https://elixir-lang.org/docs.html)
* Allow searching for the projects listed on the official docs page

**Comment by ericmj** [comment]
Not sure exactly what you are requesting but we can't list the core elixir libraries on hex.pm because they are not Hex packages. If we listed them people would think they can download them as packages.

**Comment by jfeaver** [comment]
Okay, that makes sense. I am mentioning this as an issue because I was surprised when I went to the Hex docs homepage and couldn't get to the core elixir libraries because I knew that they were hosted on the hex docs site. That surprise felt like a bug.

It would also be really convenient if I could have just one bookmark that leads me to core elixir documentation as well as elixir package documentation.

**Comment by ericmj** [comment]
Where would you expect to find documentation to core docs and package docs?

On the https://elixir-lang.org/docs.html page there are links to Elixir core docs and in the top-right corner there is a link to https://hex.pm.

Elixir core docs were added to hexdocs as a convenience for users to have single place to find Elixir documentation, but the Elixir core applications will not be visible on https://hex.pm because they are not Hex packages.

On the front page of https://hexdocs.pm there is a search form for all packages. I have created a PR so that Elixir core applications are returned in the search results https://github.com/hexpm/hexdocs-static/pull/8.

**Comment by jfeaver** [comment]
Awesome! The hexpm/hexdocs-static#8 PR is a great solution. I imagine there could be a dropdown menu next to the right or left of the "Documentation" dropdown that says "Core" and lists those same documentation links. Thanks for adding the core apps to search results!!

**Comment by ericmj** [comment]
PR is merged.
