### ISSUE TITLE
Add WebDAV Hexpm.Store

### ISSUE THREAD

**Issue by savonarola** [hexpm/hexpm#568]
Hello!

In our company we often work with code which unfortunately can't be legally transferred to external services like hex.pm or AWS S3. So currently we use internal packages through `git:`option in `mix.exs`.

A possible option would be maintaining an internal instance of `hexpm`, but currently it has only one production-ready `Hexpm.Store`: S3. It would be great to have a `Hexpm.Store` for some easily configurable local network storage like WebDAV.

So, would it be of any use to implement a WebDAV `Hexpm.Store` for `hexpm`?

**Comment by wojtekmach** [comment]
Hello! We don't have plans to implement or maintain other `Hexpm.Store` implementations in this repo. However, it should be fairly straightforward to fork `hexpm`, build webdav implementation and configure your hexpm instance to use that instead [1].

Depending on your organization, running `hexpm` as your private repository might be an overkill though, because it has extra stuff like users management, download counters etc. So if you just want to store package tarballs _somewhere_ it might be an overkill. Unfortunately we don't have a readily available alternative yet. Repository API is fully specified [2] so you have an option to build an implementation yourself. If you just want a read-only repo and are OK with manually pushing tarballs then it's really easy. Furthermore, I'm actually working on a minimal repo implementation [4]. It's not finished yet, but the idea behind the project is for folks to either use that directly or to fork and make small changes to match their needs.

Btw, in Hex client v0.17 we exposed configuration to use external repos, see [3].

[1] https://github.com/hexpm/hexpm/blob/90d008e8187cd88c57222d5a8b53a49ed1efd470/config/config.exs#L25
[2] https://github.com/hexpm/specifications/blob/master/endpoints.md#repository
[3] https://hex.pm/docs/tasks#hex_repo
[4] https://github.com/wojtekmach/mini_hex

**Comment by wojtekmach** [comment]
I'm gonna close the issue but feel free to continue discussion here.

**Comment by savonarola** [comment]
Thanks for the detailed answer.

Having API specification, implementing some minimal readonly repo from scratch (or through forking mini_hex) sounds reasonable.
