### ISSUE TITLE
Broken links through Google

### ISSUE THREAD

**Issue by wnederhof** [hexpm/hexpm#570]
When trying to access Hex through Google, for example when searching for "phoenix generate model types", I find addresses such as:

https://hexdocs.pm/phoenix/Mix.Tasks.Phoenix.Gen.Model.html

Which is broken, and similar search queries lead to broken links as well. Did something change in the routing maybe?

**Comment by wojtekmach** [comment]
So the problem is https://hexdocs.pm/phoenix always points to the latest version, which as of right now is v1.3.0. In that version, `Mix.Tasks.Phoenix.Gen.Model` is deprecated and does not show up in the docs. Note the link works when v1.2.0 is used explicitly: https://hexdocs.pm/phoenix/1.2.0/Mix.Tasks.Phoenix.Gen.Model.html

**Comment by ericmj** [comment]
We are moving hexdocs from static file hosting to run as a proper application. When we have done that we can start improving things like this since the hexdocs application can look at all phoenix versions and generate redirects or links to older versions. Right now it's impossible to fix because hexdocs just hosts files that package owners uploads.

Another idea would be to add a module attribute `@deprecates_module {Mix.Tasks.Phoenix.Gen.Model, "explanation..."}` that ex_doc can use to generate html files with links from the deprecated module to the new module.

**Comment by ericmj** [comment]
@josevalim What do you think about adding a `@deprecates_module` attribute?

**Comment by ericmj** [comment]
Closed due to lack of activity.
