### ISSUE TITLE
Document difference between password and passphrase

### ISSUE THREAD

**Issue by dukedave** [hexpm/hexpm#588]
When following [**Authenticating on CI and build servers**](https://hex.pm/docs/private) on a fresh install I got:

```
$ mix hex.organization key acme
** (Mix) No authorized user found. Run 'mix hex.user auth'
```

I followed the instructions:

```
$ mix hex.user auth
Username: dukedave
Password:
Generating API key...
Encrypting API key with user password...
```
:arrow_up: I _assumed_ `password` was my http://hex.pm one, and that seemed to work.

Then I tried again:
```
$ mix hex.organization key acme
Passphrase: 
** (Mix) Wrong passphrase

If you forgot your passphrase, you can reset it using `mix hex.user reset password` or on the hex website: https://hex.pm/password/reset
```

:arrow_up: this is the first time I've met the term `passphrase` and I didn't know what to do.
I tried making up a new one, but that caused the `Wrong passphrase` error.

I tried a second time using my http://hex.pm password as `passphrase` and it worked.
This implied that they are the same thing (and it's just inconsistent naming), but then:

https://github.com/hexpm/hex/issues/250 implies that `password` and `passphrase` have intentionally different meanings.

Can someone who knows better update [the docs](https://hex.pm/docs/private) to clarify?

**Comment by ericmj** [comment]
The passphrase is used to encrypt your local API key, we always ask for the passphrase except for when creating the API key. The key is created with `mix hex.user auth` and will ask for your hex.pm account password. By default the password is used as encryption passphrase. So to sum up, password is your account password, passphrase is what we use to decrypt the API key.

The reason we keep passphrase and password separate is because if you change the account password the passphrases for your API keys stays the same because they are locally encrypted.

We should try to make this less confusing but I'm not sure how to do that without changing how we do API authentication.

**Comment by josevalim** [comment]
Maybe "Local password" and "Server password"?

**Comment by wojtekmach** [comment]
we're moving forward with "local password" & "account password" which has some additional explanation in Hex client.
