### ISSUE TITLE
Add docs_url to API package payload

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexpm#636]
This way we can:
- remove hardcoded `https://hexdocs.pm` URLs from Hex client
- give more flexibility to the servers, e.g. docs for private packages can be hosted on a different domain
- while at it, we can deprecate `has_docs` field

@ericmj thoughts?

**Comment by wojtekmach** [comment]
Ok, the problem with _not_ hardcoding hexdocs.pm in Hex client anymore is for `mix hex.docs online ecto` we'd have to call API to grab the URL instead of opening known URL which is not ideal.

I still think it would be nice to have docs_url though but maybe yagni... If we add it, it probably should be called `docs_html_url` in case someday we'd want to have `docs_tarball_url` (e.g. https://repo.hex.pm/docs/ecto-2.2.8.tar.gz)

Maybe the way to solve it on the client to not hardcode url in code is to keep base docs_html_url in `~/.hex.config` per repo.

**Comment by ericmj** [comment]
> * remove hardcoded https://hexdocs.pm URLs from Hex client
> * give more flexibility to the servers, e.g. docs for private packages can be hosted on a different domain
> * while at it, we can deprecate has_docs field

Yes, please! These are all great points.

I see no problem with hitting the API to get the URL for `mix hex.docs online ecto`. It feels semantically more correct also since docs being in the repo is an implementation detail and not specced afaik. This is even more important for orgs since the url will probably be `myorg.hexdocs.pm/mypackage`.

It will also fix the confusion about repo/org in `hex.docs` I think. It was wrong to involve repos at all, we should have not put the repo name in the directory path and instead treat everything as orgs unless we add a `--repo` flag in the future.
