### ISSUE TITLE
Allow to pay full X for Y amount of engineers

### ISSUE THREAD

**Issue by yordis** [hexpm/hexpm#644]
I want to be able to pay for specific amount of years (or maybe months) for specific amount of engineers instead of paying in monthly bases.

**Comment by ericmj** [comment]
We are currently working on annual billing to pay on an yearly basis instead of each month.

But I think you want some specific features implemented, if that's the case then we should start with discussing those features. Since Hex is open source you can then pay for someone to work on the features and the Hex team will of course help and support them as much as we can.

**Comment by yordis** [comment]
@ericmj I am fine with either one, I just want to pay the Org yearly basis so it is easier to manage.

**Comment by ericmj** [comment]
This is being worked and features that are paid-only are tracked internally so I will close this issue. Thank you for the feedback!
