### ISSUE TITLE
New page for "Show all versions" on package page

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#727]
Today, when clicking "Show all versions" on the package page it expands to the full list of versions.

<img width="240" alt="screenshot 2018-10-05 at 17 35 44" src="https://user-images.githubusercontent.com/316890/46545141-cbe9a680-c8c5-11e8-8777-5cddc1965efb.png">

For some packages this list is becoming too long so instead of expanding the list we should link to a new page that lists all versions.

In the future we can add more features to this page. For example showing the retirement reason inline, hiding pre-releases (after a stable version has been released) and retired versions by default.

**Comment by wojtekmach** [comment]
👍

**Comment by janpieper** [comment]
I would suggest to link "Show all versions" to `/packages/:name/versions` to list all available versions on a separate page instead of using this _drop-down_-like function, when there are more than x versions available.

Maybe we can move `/packages/:name/:version` to `/packages/:name/versions/:version` via a `301 Moved Permanently` response to avoid mixing `/packages/:name/:version` and `/packages/:name/versions`.

What do you think?

**Comment by wojtekmach** [comment]
@janpieper yes, we definitely want a separate `/packages/:name/versions` page. Regarding redirect that's probably ok too but I'd do that in a separate step once we ship versions page.
