### ISSUE TITLE
Organization owned public packages

### ISSUE THREAD

**Issue by ericmj** [hexpm/hexpm#751]
## Background

Currently each organization has its own repository and namespace sharing the organization's name where they can publish their private packages. Organizations can manage their members and the members permission levels so that all users in organizations can share fetch and publish access to the private packages.

Users can publish packages publicly or to a repository of an organization they are member of. A package can have multiple users as owners with different ownership levels, either "maintainer" or "full", where the only difference is that full owners can remove and add other package owners.

## Problem

Organizations have good tools for managing their private packages there are no similar tools for public packages. This makes it unfeasible to easily manage public packages where the ownership (being able to publish primarily) is shared across the whole organization.

## Solution

The idea is to make organizations act like users with some restrictions around how organizations can own packages. Additionally to make the ownership levels more clear we will rename the "full owner" to "admin" and the "maintainer" level to "collaborator".

Organizations will be able to be accessed via `https://hex.pm/users/acme`, just like regular users, where their public packages will be listed along with their social media information. This can be useful for companies that want to promote their open source contributions.

The first time a package is published the user should be prompted to select an organization to publish the package to (or leave blank to own the package yourself). We will only do this if the user is member of any organizations.

We add the restriction that a package with an organization as admin can not have any collaborators outside of the organization, this means only organization members will have access to the package (this restriction may be lifted in the future after we are sure we design the UX so that outside users are not accidentally given access to the package).

The exception to previous rule is that when an organization owns a package, organization members can still be added as collaborators. This is useful when you want to give fine-grained publish access to members with the "read" permission level.

Additionally, organizations can not be added as collaborators to packages and when an organization is the admin of a package no other users or organizations can be admins.

The `mix hex.owner` task will be extended to work with both users and organizations. Also add a `mix hex.owner transfer package acme` for transferring ownership of a package, it removes all current owners and adds the new one as admin. This is useful when moving a package to an organization.

## Other notes

Important to note is that this will not add public namespaces/repositories. An organization's public packages will still be published to the global "hexpm" repository and the organization's own repository will be reserved for private packages only.

If organizations will act like users we need to make sure that no organizations and users share names. We have already contacted organizations and users about this in the past but some have not yet changed name. We will contact them again and give them time to change their names.

## Future discussions

Backend implementation details.

Ensuring API backwards compatibility for `/api/packages/:name/owners` endpoint.

**Comment by bryanhuntesl** [comment]
It's been a while…

We created an organisation subscription thinking we could put our projects under the ownership of esl (hex.pm) organisation and have a team of people managing them.

What we want is that if our people are working on open source projects and they leave or walk under a bus we can still manage the projects, pushing updates if necessary, and generally keeping the ecosystem alive and healthy

Sometimes people just quit Elixir/Erlang and go program language X,Y,Z and never look back - it's normal. Not everyone is willing to spend the effort maintaining an open-source library long term. Just look at github and the number of projects ignoring issues and PR for years if you want a good example of what maintainer rot looks like ([for example](https://github.com/zeromq/erlzmq2/pulls)).

The packages sit there gathering dust with nobody providing updates, the only solution is to fork, and it creates and unholy mess of broken legacy dependencies. 

ESL is willing to spend money making and publishing open-source libraries - purely for the good/health of the ecosystem - I’m sure other companies would too.

In the case that we’re using a package internally, meaning it’s private, we aren’t going to be pushing it to hex.pm anyway (security audits etc) and our build systems already need to deal with the fact that they need to check out a lot of other dependencies from git (SSH) so that’s covered (but what a pain).

Any chance of implementing this so it can be a useful feature and we can give you some money for an enterprise account ?

**Comment by ericmj** [comment]
Sorry for the delay on this. The implementation turned out to be more complex than first planned because it touches everywhere we do any authorization related to package ownerships which touches a lot of different places of the code base. I had to scrap the first implementation and start on a new more general approach so that we can reuse more code. I am currently working on the new implementation.

@bryanhuntesl What you are describing is the exact use case we have in mind. I can't give a time estimate when this will be complete unfortunately, but it will be the next feature for hex.pm.

**Comment by bryanhuntesl** [comment]
Much appreciated Eric - thanks for the update.

**Comment by ericmj** [comment]
This feature is now released. See the release announcement: https://hex.pm/blog/hex-v0.20-released.

**Comment by bryanhuntesl** [comment]
Eric you legend
