### ISSUE TITLE
Add option or CLI flag to disable version overriding for private packages

### ISSUE THREAD

**Issue by whatyouhide** [hexpm/hexpm#855]
We use private packages at work, and we'd like to have the same behavior we have with public packages with regard to overriding existing versions (that is, we want our private Hex repo to be immutable like the public one). I spoke with @ericmj and he told me this can be an option either in the organization dashboard on the website, or through CLI. I'd prefer CLI so that it can be enabled on a case by case basis, my 2c :)

**Comment by wojtekmach** [comment]
On CLI, and on a per-package basis (you can do it globally if you want too) this could be done as the following:

```
defmodule MyApp.MixProject do
  defp project() do
    hex: [
      override_releases: false
    ]
  end
end
```

would that work for you?

Alternatively, instead of opting out of release overrides we could opt-in, by default don't allow them but on publish, just for private packages, provide a really good error message how to enable them. This way, we'd avoid accidentally overriding releases (which people might have already doing without realising) as well as make this option more discoverable.

Thoughts?

**Comment by wojtekmach** [comment]
An advantage of having this option on the website is it's super obvious as well as we could add audit log entries whenever this option is toggled. The disadvantage of website approach is it would be awkward to build per-package toggle inside current UI, so it would likely be just a global setting per org.

**Comment by whatyouhide** [comment]
I'm for the `override_releases: false | true` option in `mix.exs` and CLI. It would solve all of our needs. I think opt-in is semantically better (because public packages work that way, so less surprising IMO), but not sure about how backwards compatible you wanna be :)

**Comment by whatyouhide** [comment]
Hey folks, any chance someone on the Hex team gets a chance to implement this? I would love to help so much but I got noooo time 😄 Thanks in advance!

**Comment by supersimple** [comment]
@whatyouhide , et al.,
I have some time in the next few days to work on this unless someone else is already started on it or really feels like doing it.

**Comment by ericmj** [comment]
I have not started working on this yet so if someone can grab it that would be great.

This requires changes on the client and the server. Right now private packages can be overridden/replaced without an explicit action, unlike public packages which cannot be replaced (after 1h). I think we should change the current default, which is to always replace the version of the private package, and instead make it an explicit action to replace the version, for example `mix hex.publish --replace`.

I don't think we should use package metadata for this since it does not describe a property of the package, instead it describes the change we are doing to the package. Because of this I think we should use query parameter, for example `?replace=true`.

**Comment by wojtekmach** [comment]
Sounds good to me. For public packages within the 1h window, would we still automatically replace or the user would have to explicitly pass `--replace` too? I’m fine with the current behaviour but I kind of like the explicitness too.

**Comment by ericmj** [comment]
That's a good question. I think we should do it if we can make the error message explain clearly that you should add `--replace` to actually replace the package, if not I would keep the current behavior.

It could be tricky because the client needs to interpret the error and show its own error message, since mix and rebar3 would likely need different error messages.

**Comment by supersimple** [comment]
I like the explicitness even within the 1 hour for public packages. @tsloughter might want to be aware of this coming change.

**Comment by whatyouhide** [comment]
I agree, having to always pass `--replace` sounds like the way to go provided we have good errors that guide users towards that.

**Comment by supersimple** [comment]
@whatyouhide I started on this already. Just need to find a little time to finish it up (i started a new job, so my OSS time is a little less than it was)

**Comment by whatyouhide** [comment]
@supersimple nice, and congrats on the new job! Thanks for tackling this :)
