### ISSUE TITLE
broken link for docs (ecto_models.html)

### ISSUE THREAD

**Issue by phiat** [hexpm/hexpm#903]
The link for 'mix task guides' (https://hexdocs.pm/phoenix/1.3.0-rc.1/mix_tasks.html#ecto-specific-mix-tasks) is broken on the ecto_models.html page  (https://hexdocs.pm/phoenix/1.3.0-rc.1/ecto_models.html)

Also broken:  the 'mix tasks' (same link) at bottom of doc.

**Comment by wojtekmach** [comment]
Hex.pm is concerned with hosting packages & docs, but not the actual contents. If the problem is  with a particular package, please report it on that project repo!

The Mix tasks guide for Phoenix is changed in v1.4: https://hexdocs.pm/phoenix/phoenix_mix_tasks.html, if there are problems with it please report it to the phoenix team.

**Comment by phiat** [comment]
Ah yes, I just came back to close this.  Sorry, keep up the good work.
