### ISSUE TITLE
Changelog section for hex

### ISSUE THREAD

**Issue by aesmail** [hexpm/hexpm#912]
This is related to #248

## SUMMARY

```
mix deps.get
# do some work and release a project
mix hex.outdated
# shows package abc could be updated from v1.2.3 to 1.2.5
mix hex.changes abc
# shows changes for abc v1.2.4 and v1.2.5
```

## DETAILS

I find myself almost always checking the changelogs for any updates to any package.
What I'm doing currently:

1. Doing `mix hex.outdated` and check for possible updates.
2. Going to the package page on hex (manually) and going to the GitHub page for that package hoping for a `CHANGELOG` file.
3. Checking the `CHANGELOG` file if it exists or skimming the commits to get a sense of what has changed.
4. Deciding whether to update or not.

Steps 2 and 3 are time consuming just because the process is manual and some packages have no `CHANGELOG` file which makes the process more time consuming.

Is it possible to *require* a `CHANGELOG` file for packages published to hex?
The file should include the changes since the previously published version. Hex could parse the changes based on version number, for example.

This way, publishers are encouraged to lay the changes out for their package users.

Maybe, the `mix hex.outdated` command could display a URL to the changelogs page along the versions info. Also, just like `mix hex.docs`, there could be `mix hex.changes` which could print out the changes for a specific version.

One more thing, changelogs could be written in a predefined format to make parsing and analyzing possible/easier, like:

```
# v1.0.3
* [security] fixed some serious security issue
* [enhancement] added more ways to handle something
* [bugfix] calling func/2 with nil returns expected result
```

This way, mix could show security changes while doing `mix deps.update`.

**Comment by aesmail** [comment]
An example of something similar is like the `pub` package manager for dart.
example: https://pub.dev/packages/xml#-changelog-tab-

**Comment by ericmj** [comment]
We don't want to require a CHANGELOG file for packages because publishing a package should be as frictionless as possible. We would also like to avoid requiring a specific format (that isn't already established) for the same reason and many packages would have to rewrite their current changelogs to publish.

Showing the changelog on the website would be reasonable. The format you suggest is a subset of markdown which is a fair assumption and I think most projects use markdown for their changelog. But rendering user provided markdown and HTML makes us susceptible to XSS attacks so we would have to research how to prevent that.

**Comment by supersimple** [comment]
I am a little hesitant to promote a user-written changelog to hex. I think we should be promoting hex diff for any serious analysis of code changes.
On the other hand, perhaps if all you want to know is if there are breaking changes we could promote that. eg. `xyz/2 requires option a starting in version 1.2.3`
I think there is already some misunderstandings on how reliable github is for reflecting changes in hex package releases and we should be careful not to promote the misconception that they are always in parity.

**Comment by wojtekmach** [comment]
> mix hex.changes abc
> # shows changes for abc v1.2.4 and v1.2.5

I think hex diff already helps with that, we can see the changelog (if package has it) in the diff output here https://diff.hex.pm/diff/ecto/3.5.3..3.5.4, as well as at the command line:

```diff
diff --git a/var/folders/r1/sfc3dkds3y9bckbc0vz1xtnh0000gn/T/ecto-3.5.3-F3E4F560/CHANGELOG.md b/var/folders/r1/sfc3dkds3y9bckbc0vz1xtnh0000gn/T/ecto-3.5.4-42E8A814/CHANGELOG.md
index 298e87b..90a855c 100644
--- a/var/folders/r1/sfc3dkds3y9bckbc0vz1xtnh0000gn/T/ecto-3.5.3-F3E4F560/CHANGELOG.md
+++ b/var/folders/r1/sfc3dkds3y9bckbc0vz1xtnh0000gn/T/ecto-3.5.4-42E8A814/CHANGELOG.md
@@ -1,5 +1,18 @@
 # Changelog for v3.x

+## v3.5.4 (2020-10-28)
+
+### Enhancements
+
+  * [mix ecto.drop] Provide `--force-drop` for databases that may support it
+  * [guides] Add new "Multi tenancy with foreign keys" guide
+
+### Bug fixes
+
+  * [Ecto.Changeset] Make keys optionals in specs
+  * [Ecto.Enum] Make sure `values/2` works for virtual fields
+  * [Ecto.Query] Fix missing type on CTE queries that select a single field
+
```

**Comment by axelson** [comment]
I have this same pain when I'm trying to upgrade a large number of dependencies, but I agree that it doesn't make sense to require a changelog file in order to publish a package. Maybe if there was an optional field that specifies a file path in the git repository, then hex could auto-generate the `% HEX_DIFF_COMMAND="git diff --color=always --no-index {__PATH1__,__PATH2__}/CHANGELOG.md" mix hex.package diff ecto 3.5.3 3.5.4` that Wojtek mentions, as well as showing the changelog link in the output of some commands.

**Comment by ericmj** [comment]
`mix hex.outdated` already displays the link to diff.hex.pm from where you can navigate to the changelog file. If you wish to custom generate diffs of specific files I think another tool should do that instead of Hex since we are going into very specific areas.

`mix hex.package diff` could support generating the diff of only a specific file, if this is what you are looking a proposal and PR to https://github.com/hexpm/hex would be appreciated.

**Comment by ericmj** [comment]
We will include the rendered README on the website's package page when we release the redesign of the website. With that functionality we could also render and display markdown changelogs, but there are no direct plans for it yet.

I think we have plenty of tools of finding and displaying the changelog today between diff.hex.pm, preview.hex.pm, `mix hex.package diff`, and `mix hex.outdated`. I am closing this for now since there are no concrete plans for further tooling around changelogs but proposals and new ideas in this area are of course always appreciated.
