### ISSUE TITLE
Unable to update profile information

### ISSUE THREAD

**Issue by ilian** [hexpm/hexpm#938]
**Description**
Users are unable to update profile information under account settings. The user is presented with a 404 error.

**To reproduce**
1. When logged in, navigate to the [profile dashboard](https://hex.pm/dashboard/profile).
2. Click the save button at the bottom of the page.

**User environment**
Firefox 75.0 on Linux

**Comment by bjornrud** [comment]
👍 Also getting this... and a little frustrated because I didn't know my email would be public... and now I can't make it private.

**Comment by n7st** [comment]
The form's attempting to PUT the data to /dashboard/profile rather than POST as specified in the form's method. This doesn't match a route, hence the 404.

This seems to be something to do with Phoenix detecting the changeset.

```html
<form action="/dashboard/profile" method="post" _lpchecked="1">
    <input name="_method" type="hidden" value="put">
```

I've fixed it locally by adding PUT routes for /dashboard/profile:

```diff
diff --git a/lib/hexpm_web/router.ex b/lib/hexpm_web/router.ex
index eb4cc4dd..89de6ceb 100644
--- a/lib/hexpm_web/router.ex
+++ b/lib/hexpm_web/router.ex
@@ -126,6 +126,7 @@ defmodule HexpmWeb.Router do
     pipe_through :browser
 
     get "/profile", ProfileController, :index
+    put "/profile", ProfileController, :update
     post "/profile", ProfileController, :update
 
     get "/password", PasswordController, :index, as: :dashboard_password
```

Or alternatively, specifying the method on the form (as removed in https://github.com/hexpm/hexpm/commit/eedad4ff47b14e49b0c5060f96bd12e53818230c).

@bjornrud it looks like if you select the "Don't show a public e-mail" option from the dropdown and press save it will update your profile in spite of the 404 error (and hide your e-mail from your profile).

**Comment by bjornrud** [comment]
@ericmj what is the turnaround for release of changes like this to the website?

**Comment by ericmj** [comment]
We don't have specific timeframes but it should be deployed in a few moments.
