### ISSUE TITLE
Increased timeouts in CI

### ISSUE THREAD

**Issue by jimsynz** [hexpm/hexpm#951]
Hi folks. Not sure if this is the right place to report this but I’ve been seeing a slowly increasing number of CI failures related to registry timeouts ([here is an example](https://gitlab.com/jimsy/kinemat/-/jobs) but it’s been happening on a number of my repos). These requests are served by a CDN, right? Perhaps they can give us some information. 

Happy to help any way I can.

**Comment by ericmj** [comment]
We have received other reports of increased number of timeout errors in CI jobs. We haven't made any infrastructure or client changes recently so the issue is a bit strange and unfortunately we don't have a lot of information to go on to investigate the issue.

When roughly did the errors start? Have you done changes to your CI around that time, for example upgrade Elixir or Erlang/OTP?

**Comment by jimsynz** [comment]
It seems to have been slowly increased over the last couple of weeks.  Most of my CI jobs run in the `elixir:latest` container, so will have had Erlang and Elixir updates applied as they become available.  Interestingly I haven't seen the issue when running `mix deps.get` manually - however I don't do that nearly as much as my CI jobs do.  What CDN do we use?

**Comment by ericmj** [comment]
Are you still experiencing this problem?

**Comment by jimsynz** [comment]
@ericmj no - it seems to have come right.  Not sure what you folks did, but it seems to have worked 😄
