### ISSUE TITLE
Wrong "Online documentation" link when newest release is retired

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexpm#995]
See below. We should link to the proper latest version, v0.15.7 in this case.

![2021-01-04 at 13 23](https://user-images.githubusercontent.com/76071/103535030-45e7ac00-4e90-11eb-8048-423a8deedebb.png)

**Comment by ericmj** [comment]
I think the issue is that we link to a pre-release version, not that the version is retired. We should match what hexdocs does and the version that is displayed at the top of the page and if IIRC they do not take retirements into account.

**Comment by leandrocp** [comment]
> We should match what hexdocs does

Hey @ericmj do you mean this https://github.com/hexpm/hexdocs/blob/29166c503d8ad7e00340c034761984d28fa5c6a2/lib/hexdocs/utils.ex#L13?

What if a version was retired and it's not a pre-release?

**Comment by ericmj** [comment]
> Hey @ericmj do you mean this  https://github.com/hexpm/hexdocs/blob/29166c503d8ad7e00340c034761984d28fa5c6a2/lib/hexdocs/utils.ex#L13?

Yes.

> What if a version was retired and it's not a pre-release?

Since that is consistently shown as the latest version on hexdocs and elsewhere on hexpm we should follow that rule here as well and display it as latest even if it was retired.

We can have a discussion about if retired versions should show up as latest but that requires a bigger change over multiple repos so I think we should still go ahead with this change before that.

**Comment by leandrocp** [comment]
> Since that is consistently shown as the latest version on hexdocs and elsewhere on hexpm [...] so I think we should still go ahead with this change before that

Sounds good. I'll update https://github.com/hexpm/hexpm/pull/996
